[package]
name = "application"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1"
sha1 = "0.10"
tokio = { version = "1", features = ["full"] }
hyper = "0.14"