[package]
name = "application"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_bencode = "^0.2"
serde = "^1.0"
serde_derive = "^1.0"
serde_bytes = "0.11"
tokio = { version = "1", features = ["full"] }
hyper = "0.14"